version: "3.5"

services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce
        restart: always
        ports:
          - "9000:9000"
        command: -H unix:///var/run/docker.sock
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /appdata/portainer/data:/data